development:
  adapter: postgresql
  encoding: unicode
  database: si_development_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: si_development_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: si_development_production
  pool: 5
  username: 
  password: 
